Update spec for 3.11 build
SUSE-Enceladus/mash-client pull request #91
Opened 2024-05-20 19:24 UTC by smarlowucf

2024-05-21 11:15 UTC, apozsuse approved these changes
LGTM

2024-05-23 12:47 UTC, rjschwei requested changes

2024-05-23 12:47 UTC, rjschwei commented on package/mash-client.spec
> +python3.11 setup.py --command-packages=click_man.commands man_pages --target man/man1
This will when `%{?sle15_python_module_pythons}` changes it's target or when building for multiple interpreters. Should be `%{python_flavor}`

2024-05-30 13:54 UTC, rjschwei approved these changes

2024-05-30 14:04 UTC, merged